/* Cactus🌵Byte Studios™ — Demo & Help Standard v1.0
   Reusable first-launch demo/help framework. No autoplay audio. */
(function(){
  if(window.__cactusByteDemoInstalled)return;window.__cactusByteDemoInstalled=true;
  const cfg=window.CACTUSBYTE_DEMO||{};if(!cfg.appId||!cfg.appName)return;
  const demoVersion=String(cfg.demoVersion||'1');
  const seenKey=`cbs_demo_seen:${cfg.appId}:${demoVersion}`,dismissedKey=`cbs_demo_dismissed:${cfg.appId}:${demoVersion}`;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const style=document.createElement('style');style.textContent=`.cbs-demo-trigger{display:grid;place-items:center;min-width:42px;height:42px;padding:0 12px;border-radius:12px;border:1px solid rgba(56,189,248,.32);background:rgba(15,23,42,.88);color:#e2e8f0;font-weight:900;cursor:pointer}.cbs-demo-backdrop{position:fixed;z-index:10000;inset:0;background:rgba(2,6,23,.84);display:none;align-items:flex-end;justify-content:center}.cbs-demo-backdrop.open{display:flex}.cbs-demo-panel{width:min(100%,760px);max-height:92vh;overflow:auto;background:#070b19;color:#f8fafc;border:1px solid rgba(56,189,248,.28);border-bottom:0;border-radius:26px 26px 0 0;padding:18px 16px calc(24px + env(safe-area-inset-bottom));box-shadow:0 -24px 70px rgba(0,0,0,.62)}.cbs-demo-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.cbs-demo-head h2{margin:0;font-size:21px}.cbs-demo-close{width:40px;height:40px;border-radius:50%;border:1px solid rgba(148,163,184,.25);background:#111827;color:#fff;font-size:22px}.cbs-demo-sub{color:#94a3b8;font-size:12px;line-height:1.5}.cbs-demo-placeholder{border:1px dashed rgba(56,189,248,.35);border-radius:18px;padding:18px;background:#0b1224;color:#94a3b8;font-size:12px;line-height:1.5}.cbs-demo-video{width:100%;border-radius:18px;background:#020617;max-height:360px}.cbs-demo-steps{display:grid;gap:9px;margin-top:14px}.cbs-demo-step{border:1px solid rgba(148,163,184,.18);border-radius:16px;padding:13px;background:#0b1224}.cbs-demo-step strong{display:block;font-size:13px;color:#38bdf8}.cbs-demo-step span{display:block;color:#cbd5e1;font-size:11px;line-height:1.45;margin-top:4px}.cbs-demo-actions{display:flex;gap:9px;margin-top:14px}.cbs-demo-actions button{flex:1;border:0;border-radius:14px;padding:13px;font-weight:900}.cbs-demo-primary{background:linear-gradient(135deg,#38bdf8,#10b981);color:#04111d}.cbs-demo-secondary{background:#111827!important;color:#f8fafc;border:1px solid rgba(148,163,184,.22)!important}.cbs-demo-check{display:flex;align-items:flex-start;gap:9px;color:#94a3b8;font-size:11px;line-height:1.4;margin-top:13px}@media(min-width:700px){.cbs-demo-backdrop{align-items:center;padding:24px}.cbs-demo-panel{border-bottom:1px solid rgba(56,189,248,.28);border-radius:26px}}`;document.head.appendChild(style);
  const backdrop=document.createElement('div');backdrop.className='cbs-demo-backdrop';backdrop.innerHTML=`<section class="cbs-demo-panel" role="dialog" aria-modal="true"><div class="cbs-demo-head"><h2>How to use ${esc(cfg.appName)}</h2><button class="cbs-demo-close" aria-label="Close">×</button></div><p class="cbs-demo-sub">${esc(cfg.intro||'A fast guided walkthrough.')}</p><div class="cbs-demo-media"></div><div class="cbs-demo-steps"></div><label class="cbs-demo-check"><input type="checkbox" class="cbs-demo-dontshow"><span>Don’t show this automatically again for this demo version. Help stays available from the top bar.</span></label><div class="cbs-demo-actions"><button class="cbs-demo-secondary cbs-demo-skip">Close</button><button class="cbs-demo-primary cbs-demo-start">Start Walkthrough</button></div></section>`;document.body.appendChild(backdrop);
  const media=backdrop.querySelector('.cbs-demo-media');if(cfg.videoUrl)media.innerHTML=`<video class="cbs-demo-video" controls playsinline preload="metadata"><source src="${esc(cfg.videoUrl)}"></video>`;else media.innerHTML='<div class="cbs-demo-placeholder"><strong>60-second demo video slot ready.</strong><br>The written MachZero walkthrough is active now. The final recording can be added after the UI is locked.</div>';
  const steps=Array.isArray(cfg.steps)?cfg.steps:[];backdrop.querySelector('.cbs-demo-steps').innerHTML=steps.map((s,i)=>`<div class="cbs-demo-step"><strong>${i+1}. ${esc(s.title||'Step')}</strong><span>${esc(s.text||'')}</span></div>`).join('');
  function close(){if(backdrop.querySelector('.cbs-demo-dontshow').checked)localStorage.setItem(dismissedKey,'1');backdrop.classList.remove('open');document.body.style.overflow='';}function open(auto=false){backdrop.classList.add('open');document.body.style.overflow='hidden';if(auto)localStorage.setItem(seenKey,'1');}
  backdrop.querySelector('.cbs-demo-close').onclick=close;backdrop.querySelector('.cbs-demo-skip').onclick=close;backdrop.addEventListener('click',e=>{if(e.target===backdrop)close()});backdrop.querySelector('.cbs-demo-start').onclick=()=>{localStorage.setItem(seenKey,'1');backdrop.querySelector('.cbs-demo-steps')?.scrollIntoView({behavior:'smooth'});cfg.onStart?.();};
  const target=document.querySelector(cfg.triggerContainer||'.topbar')||document.body;const trigger=document.createElement('button');trigger.type='button';trigger.className='cbs-demo-trigger';trigger.textContent='Help';trigger.setAttribute('aria-label',`How to use ${cfg.appName}`);trigger.onclick=()=>open(false);target.appendChild(trigger);window.openCactusByteDemo=()=>open(false);
  if(cfg.firstLaunch!==false&&localStorage.getItem(seenKey)!=='1'&&localStorage.getItem(dismissedKey)!=='1')setTimeout(()=>open(true),Number(cfg.autoDelayMs)||900);
})();
